# import package
import turtle
turtle.Screen().bgcolor("cyan")
turtle.up()
turtle.hideturtle()
turtle.sety(100)
turtle.setx(100)
turtle.fillcolor('#f04d75')
turtle.begin_fill()
def new():
    turtle.circle(100,extent=72)
    turtle.left(90) 
    turtle.forward(100)
for i in range(5):
    new() 
    turtle.end_fill()  
    turtle.fillcolor('#f04d75')
    turtle.begin_fill()
    turtle.backward(100)  
    turtle.right(90) 
turtle.sety(100)
turtle.setx(100)
turtle.fillcolor('cyan')
turtle.circle(120,360)
turtle.end_fill()  
turtle.done()